### ISSUE TITLE
Catching NaNs during runtime

### ISSUE THREAD

**Issue by pminak** [nextsimdg/nextsimdg#158]

**Comment by draenog** [comment]
In C/C++ on system with glibc it can be done like:
```
#include <cmath>
#include <fenv.h>

int main() {
    double x, y;
    feenableexcept(FE_ALL_EXCEPT);
    x = -1;
    y = log(x);
    return 0;
}
```
It raises SIGFPE on all floating point exceptions which usually causes core dump. With Intel compilers in order to be effective it is necessary to enbable floating point exceptions with option -fp-model. With g++ it becomes ineffective with some compiler flags like -Ofast.
