### ISSUE TITLE
Clean up how to handle Catch

### ISSUE THREAD

**Issue by timspainNERSC** [nextsimdg/nextsimdg#248]
Two related problems:

1. Catch2 is probably the least common library that we use. Since it is—as we use it—just a single header, it should be easy for a user building the model to specify the location of the Catch 2 header and for it to be located by CMake.
2. The modern version of Catch2 is not the single header version any more.

## Adding a non-system header
One way of specifying the location is to follow the commands on [this page](https://cliutils.gitlab.io/modern-cmake/chapters/testing/catch.html) under the heading 'Vendoring' (whatever that means).

```
set(CATCH_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/extern/include)
add_library(Catch2::Catch2 IMPORTED INTERFACE)
set_property(TARGET Catch2::Catch2 PROPERTY INTERFACE_INCLUDE_DIRECTORIES "${CATCH_INCLUDE_DIR}")
```
where the header itself is at `extern/include/catch2/catch.hpp`.

## Replacing Catch
The header-only library [doctest](https://github.com/doctest/doctest) seems to be a replacement for the single header version of Catch2. It is available on Homebrew, at least, and is available in Ubuntu Jammy Jellyfish as `doctest-dev`. Even so, I would guess it is even less commonly available on HPC than Catch2, so we would need a robust solution to ensure it was always available. As doctest is MIT-licensed, this might be to include it in the source distribution by default.

**Comment by einola** [comment]
A few (perhaps disjointed) thoughts on this

Catch2 not being available on HPCs:
 1. We could have an option of disabling unit tests at compile time, eliminating the need for having Catch2 available. The assumption being that these won't be needed on production machines.
 2. We could have cmake download (and compile) Catch2 if it can't find it.
 3. We could include the Catch2 header files in the nextsimdg repository.

I've written these options out in my initial order of preference. It seems to me that option 1 is the easiest but still acceptable, while option 2 is perhaps the most elegant. Option 3 means we have to ensure the Catch2 headers in nextsimdg are up to date, which is extra maintenance work.

To replace or not to replace Catch2:
 - I understand that moving to the new Catch2 requires substantial reprogramming of the unit tests. Is that correct, and how substantial is it compared to switching to doctest?
 - Are there other reasons to switch, besides header-only vs. library?
 - If we take options 1 or 2 above, we don't have to switch to doctest (although we still can).

**Comment by timspainNERSC** [comment]
On the first point:
If we do include the testing library, we could just make sure we have the most up-to-date version as part of the preparation for a release of the model. Instead, that is, of monitoring the library repo for changes. I'm becoming more in favour of option 3 (distribute the library along with the code), as long as we are using a single-header library (doctest or old Catch).

For me, at least, I've liked the simplicity of (old) Catch since I was first introduced to it at UCL. Add one single header and you can write a few tests. The new design of ctah, with a separate compilation and multiple headers that I have to learn what each one does is certainly more of friction point to actually writing tests.
I don't think adapting the tests to nu-Catch will change the logic all that much, just what headers need to be included in each test source file. And also the necessary changes to the CMakeLists files.
Moving to Doctest will likely involve more changes to the test code, less to the CMakeLists files and, importantly to me, no changes at all to how I think about writing test case files.

I also note that Doctest has a MPI enabled version, with an example, which is either non-existent or not obvious on the Catch repo.

**Comment by a-smith-github** [comment]
So my perspective on this is skewed (generating code and simulating deployment/numerical verification for different embedded hardware) but my (quite general) two cents:

Testing on the customer's platform is quite a useful feature in and of itself. Not only as a baseline for scientific reproducibility but it provides concrete feedback to the user that the build worked correctly on their system. Different hardware can display different behaviours and as we only test on two systems (and currently don't fail on compile warnings) and two compilers, we can't guarantee that our production code works on a customer computer and they would need to establish this. As we add other features like XIOS and MPI where we run on multiple interdependent processes which need to communicate with each other and across nodes, we expose more system-dependent issues where it becomes useful that the user knows their system is configured correctly for our code and vice versa. 

If we were to remove tests from the default compile option, we'd still realistic want to provide some kind of debug/test flag for CMake which we'd expose publicly so that users could verify numerical accuracy the above cases. Making it non-default means we'd catch less field bugs (which hopefully they would report back to us and we'd fix) but means field bugs become non-blocking - although this isn't necessarily inherently a good thing. 

Given all that, we'd want to continue the current level of support anyway so it's probably to upgrade to new Catch2 (headers are multiple now and some renaming but otherwise not that much visible change - from the documentation anyway), or move to a new framework e.g. doctest but would go to a library based testing framework too as there are many popular ones inclduing Google Test, CppUnit, Boost Test. We already require boost as a library so although re-writing might be harder, this might be the simple option. 

In terms of reproducibility, I like the idea of shipping a testing framework in some kind of extern folder (then we have control over the existence of the source files for that framework) but there's nothing stopping us just specifying a version for each of our releases if licensing becomes an issue. If we were to use release versioning on our repo then we could control/specify which version of the test framework is supported for our nextsim-dg release and advance it when we were ready. 

If we were to change testing library, doing it sooner is probably better than later in terms of minimising engineering effort although this may impact milestones. 

XIOS is probably even more obscure than Catch2 and doesn't use CMake so it requires a few more steps. My thinking was letting the user specify the install location via environment variable or CMake argument if it cannot be found (an error would throw and instructions would be given to do this or we would do this in the first instance). Something similar could be done for Catch2 if it cannot be found on the users system.

`CATCH_INCLUDE_DIR` would be inferred from a `CATCH_DIR` set by the user

**Comment by einola** [comment]
Ok, let's proceed like this:

First, we include the (outdated) Catch2 in the neXtSIM_DG repository. It's more than just including the single ``catch.hpp`` file somewhere, but it shouldn't be too difficult.

Then, we decide what to replace the Catc2 with. The options are

- The new version of Catch2: Requires the least amount of rework for current tests(?)
- Doctest: Single-header library and easy to include in our repository.
- Boost tests: Because we use boost already.
- Something else: We can still be open to other options, but that door is closing fast.

**Comment by timspainNERSC** [comment]
As far as the tests I have written go (which is almost all of them), I believe the only changes required to move to doctest will be to:
1. rename the test definition macro (`CATCH_CONFIG_MAIN`-> `DOCTEST_CONFIG_IMPLEMENT`)
2. replace the header itself (`"catch2/catch.hpp"` -> `"doctest/doctest.h"`), and
3. use a namespace on `Approx`.

**Comment by einola** [comment]
So let's go with doctest since we like it, and implementing Catch2 with doctest is minimal effort. We can also go straight for the Catch2 to doctest switch instead of first including Catch2 v1 in our repository.

**Comment by timspainNERSC** [comment]
This was merged nearly two months ago! Closing.
