### ISSUE TITLE
Compiler support of macOS

### ISSUE THREAD

**Issue by pminak** [nextsimdg/nextsimdg#39]
When we test on macOS what compiler we have in mind? gcc (from homebrew) or clang (default Xcode or homebrew).
For example there is an issue with OpenMP.

When we want to add find_package(OpenMP) to Cmake, it not trivial to compile the code with threads with clang.

This is workaround for 
CMakeLists.txt (it selects the brew clang compiler that only supports openmp; the default one that comes with Xcode doesn't):
set(CMAKE_C_COMPILER "/usr/local/opt/llvm/bin/clang")
set(CMAKE_CXX_COMPILER "/usr/local/opt/llvm/bin/clang++")
set (CMAKE_EXE_LINKER_FLAGS "-Wl,-rpath,/usr/local/opt/llvm/lib -L/usr/local/opt/llvm/lib -lomp" )
set (CMAKE_SHARED_LINKER_FLAGS "-Wl,-rpath,/usr/local/opt/llvm/lib -L/usr/local/opt/llvm/lib -lomp" )

Not high priority but always nice to have this clean.

**Comment by timspainNERSC** [comment]
The equivalent paths on ARM64 Macs (for example, mine) are:
```
set(CMAKE_C_COMPILER "/opt/homebrew/opt/llvm/bin/clang")
set(CMAKE_CXX_COMPILER "/opt/homebrew/opt/llvm/bin/clang++")
set (CMAKE_EXE_LINKER_FLAGS "-Wl,-rpath,/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/llvm/lib -lomp" )
set (CMAKE_SHARED_LINKER_FLAGS "-Wl,-rpath,/opt/homebrew/opt/llvm/lib -L/opt/homebrew/opt/llvm/lib -lomp" )
```
We should at least be factoring out the Homebrew prefix.

**Comment by auraoupa** [comment]
I am not a big fan of putting path in makefiles, could it be possible to isolate those lines in separate files that would be called inside a CMakeLists.txt ? That way CMakeLists.txt stays generic and some make_homebrew.txt and make_llvm.txt are maintained separately. Or maybe we call this files CMakeLists_homebrew.txt and CMakeLists_llvm.txt and do a link before compiling to CMakeLists.txt ? What do you think ?

**Comment by timspainNERSC** [comment]
Now that I give it some thought, aren't CMAKE_C_COMPILER and CMAKE_CXX_COMPILER usually defined in the (command line/IDE) environment and just used in the CMake files? Precisely so that there are no system dependent paths inside the CMake files. The LINKER_FLAGS feel like they are a similar situation, too.

**Comment by einola** [comment]
I'm not familiar with ``cmake``, but in make you usually assume that ``CC``, ``CXX``, ``FC``, etc are defined in the environment. I would suggest that we have separate environment files, like @auraoupa suggests, so that the basic ``CMakeLists.txt`` file is platform agnostic.

In general though, we should set up a separate repository in the nextsimdg organisation. Called something like "environment". In there, we can then store setups for different machine types and IDEs. A structure could look like

```
nextsimdg
|- environment
    |- mac_homebrew
        |- nextsimdg.src etc with values from @pminak 
    |- mac_macports
        |- files
    |- Eclipse
        |- files
    |- etc. etc.
```

Sound ok? If we agree, can @auraoupa set up the repository?

**Comment by pminak** [comment]
@einola I would just include this as information in documentation (docs on installation). @timspainNERSC is right that flags are defined outside cmake. 
It's a question of maintenance, I would support default configuration on linux and mac, and mention in documentation other options.

**Comment by timspainNERSC** [comment]
Since we have multiple people successfully compiling on macOS, I think this issue can be closed.
